#! /usr/bin/python3

import numpy as np
import pandas as pd
import argparse
import subprocess

TIMES = 7


parser = argparse.ArgumentParser(description='.')

parser.add_argument('-j', '--java', type=str, nargs="+" , required=True)
parser.add_argument("-a", '--args', type=str, nargs="+")

args = parser.parse_args()

bins = vars(args).get("java")
argList = vars(args).get("args")
out = np.zeros((len(bins), len(argList)))
x = 0
y = 0

for bin in bins: 
    for arg in argList:
        median_times = []
        command = "java " + bin + " " + arg
        for i in range(TIMES):
            time = subprocess.check_output(command.split(), stderr=subprocess.PIPE)
            median_times.append(time)
        median_times.sort()
        out[x][y] = median_times[3]
        x = x + 1
    x = 0
    y = y + 1

df = pd.DataFrame(out, argList, bins)
df.to_csv("results.csv")
