#! /usr/bin/python3

from statistics import median
import numpy as np
import pandas as pd
import argparse
import subprocess

parser = argparse.ArgumentParser(description='.')

parser.add_argument('-j', '--java', type=str, nargs="+" , required=True)
parser.add_argument("-a", '--args', type=str, nargs="+")

args = parser.parse_args()

bins = vars(args).get("java")
argList = vars(args).get("args")
out = np.zeros((len(bins), len(argList)))
speedup = np.zeros((len(bins)-1, len(argList)))
basetimes = np.zeros(len(argList))


x = 0
y = 0

# Run each java program for each argument
for bin in bins: 
    for arg in argList:
        command = "java " + bin + " " + arg
        time = subprocess.check_output(command.split(), stderr=subprocess.PIPE)
        time = str(time)[2:len(str(time))-3]
        time = str(time).split('\\n')
        time.sort()
        median = float(time[len(time)//2])/1000
        out[x, y] = median
        if x == 0:
            basetimes[y] = median
        else:
            speedup[x-1, y] = median / basetimes[y]
        y = y + 1
    y = 0
    x = x + 1

df = pd.DataFrame(out, bins, argList)
df.to_excel("results_2.xlsx", sheet_name="Time tables")

bins.pop(0)
if (len(bins) != 0):
    df = pd.DataFrame(speedup, bins, argList)
    df.to_excel("results.xlsx", sheet_name="Speedup tables")


print("Tables generated. Check results.xlsx")

