#! /usr/bin/python3

from statistics import median
import numpy as np
import pandas as pd
import argparse
import subprocess

TIMES = 7


parser = argparse.ArgumentParser(description='.')

parser.add_argument('-j', '--java', type=str, nargs="+" , required=True)
parser.add_argument("-a", '--args', type=str, nargs="+")

args = parser.parse_args()

bins = vars(args).get("java")
argList = vars(args).get("args")
out = np.zeros((len(bins), len(argList)))
x = 0
y = 0

for bin in bins: 
    for arg in argList:
        command = "java " + bin + " " + arg
        time = subprocess.check_output(command.split(), stderr=subprocess.PIPE)
        time = (str(time)[2:len(str(time))-3])
        time = str(time).split('\\n')
        time.sort()
        out[x, y] = float(time[3])/1000
        y = y + 1
    y = 0
    x = x + 1

df = pd.DataFrame(out, bins, argList)
df.to_excel("results.xlsx")
print("Results.xlsx is create : )")

